### ISSUE TITLE
Implement differentiation of templated functions.

### ISSUE THREAD

**Issue by vgvassilev** [vgvassilev/clad#10]
For example:

```
template<typename T> T F(T x) { return std::sin<T>(x); }
```

**Comment by vgvassilev** [comment]
This has been completed years ago. We have `test/Gradient/Gradients.C` and `test/FirstDerivative/FunctionCalls.C`

However, if the issue meant to be able to differentiate an entire template pattern (the thing with the `T`s) not a template specialization (the thing which replaces the `T`s with a concrete types). Theoretically we might want to differentiate the template patterns if we have a library and we want to print out source code. The problem is that we cannot express the differentiation request with syntax C++ and as of today I cannot see a practical application. Let's reopen if that changes.

**Comment by davidlange6** [comment]
Can we add a link to the relevant test (as Gradients.C is kinda big...) - I see

https://github.com/vgvassilev/clad/blob/master/test/Gradient/Gradients.C#L764

which I wonder if the template even survives some optimization? as ```const size_t m = maxN < N ? maxN : N;``` seems a strange construct to me. [FunctionCalls.C was less obvious to me]
