### ISSUE TITLE
Add support of arrays in both modes

### ISSUE THREAD

**Issue by efremale** [vgvassilev/clad#118]
Basic example:
```
double f(double a, double b, double c) {
  double coef[3] = { 1.0, 2.0, 3.0 };
  return coef[0]*a + coef[1]*b + coef[2]*c;
}
```
Additionally, we should add array inputs.

**Comment by grimmmyshini** [comment]
Hey!

The amount of support for arrays mentioned here is already available in Clad, the related tests for the same are mentioned under `Arrays.C` .Differentiation of functions with vector inputs is being tracked here: #12 I believe this issue can safely be closed.

**Comment by vgvassilev** [comment]
Thanks for investigating!
