### ISSUE TITLE
Add support for vector of points

### ISSUE THREAD

**Issue by vgvassilev** [vgvassilev/clad#12]
Support double f(double*, unsigned numElements); The user should be able to specify the independent variable from a given array of variables.

**Comment by vaithak** [comment]
- We already support the differentiation of user-defined structs or types and have good tests for these cases:
  - Forward mode: https://github.com/vgvassilev/clad/blob/master/test/ForwardMode/UserDefinedTypes.C
  - Reverse mode: https://github.com/vgvassilev/clad/blob/master/test/Gradient/UserDefinedTypes.C
- Also, the use case of `double f1(double* pts, size_t numElements) {...}` is already supported and is contained in the test cases here: https://github.com/vgvassilev/clad/tree/master/test/Arrays
- For the support of stl vectors and iterators, we have issues to track them here: #750, #751.

So, this issue can be closed as Clad already supports some of the cases or has issues tracking the other requirements.
