### ISSUE TITLE
Clad is not considering truncation of variables inside function for differentiation

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#198]
```
double f(double x) {
  int a = x;
  return 4*x*x*x + 5*a*a;   //basically 4*x^3 + 5*floor(x)*floor(x), where floor = floor function
}
```
For this function, Intuitively variable `a` should be treated as `floor function of x`. And thus differentiation should be done accordingly. For floor functions differentiation should be undefined at integral points and 0 for non-integral points.  
But in the program result is same whether type of `variable a` is `double` or `int`, and `variable a` is not being considered as floor function of x

For calcuating derivative of this function I have used this code, 
```
int main() {
  double x_val = 2;
  auto f_dx_1 = clad::differentiate(f, "x");
  std::cout << "f_dx_1.execute(x_val) = " << f_dx_1.execute(x_val) << "\n";
// f_dx_1.execute(x_val) = 68 // output 
}
```

**Comment by grimmmyshini** [comment]
Hey! 

I believe that, with the current logical infrastructure, equating truncation to a ```floor``` might not be entirely correct. My reasons are as follows:

1) A lot of time users include conversion of types such as that without intending for that conversion to imply a ```floor```. So implementing this suggestion may break a lot of that code.

2) A lot of implicit casting takes place behind the scenes and more often than not it doesn't entail a ```floor```.

I suppose it would be rightful to set the derivative of ```floor``` and ```ceil``` 0 in the context that they return the result in the same data type (i.e using the built-in ceil and floor functions). so,

for something like this:
```cpp
double x = 45.7;
double a = floor(x);
```
but should not hold for something like this:
```cpp
double x = 45.7;
int a = x;
```

***Although...***

One can argue that we should not be differentiating ints/char/booleans at all, that is the derivative of those types should always be 0 or undefined as the usual arithmetic rules are defined for real/complex numbers (equivalent to std::complex, double, float, etc). However, that is something we don't currently follow. So, if we were to integrate these changes, we need to think about what that implies for the other int/char/bool differentiation. 

I suppose, for now, a warning for assignments like that should suffice; integration of the actual suggested changes requires some discourse.

**Comment by vgvassilev** [comment]
@grimmmyshini, I agree with you. Assuming implicit narrowing conversions being a `floor` function can make a lot of damage just to support that idiom. Is there performance implications of using `floor` instead? 

@grimmmyshini, perhaps that discussion can be captured in a "limitations" section in the README?

**Comment by grimmmyshini** [comment]
> @grimmmyshini, I agree with you. Assuming implicit narrowing conversions being a `floor` function can make a lot of damage just to support that idiom. Is there performance implications of using `floor` instead?

Not that I am aware of. A quick search brought up [this](https://stackoverflow.com/questions/3300290/cast-to-int-vs-floor) which brings up a more serious issue, i.e truncation **CANNOT** be equivalent to ```floor``` for real numbers as (and I quote from the post):

*"Casting to an int will truncate toward zero. floor() will truncate toward negative infinity. This will give you different values if bar were negative."*

So for now, I think we should let this be. Until we want to go ahead with the kind of logic I mentioned in the second part of the post. 

> @grimmmyshini, perhaps that discussion can be captured in a "limitations" section in the README?

Sure! Will do.
