### ISSUE TITLE
Compile time error while differentiating constant member functions

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#199]
Minimum Reproducible Example:
```c++
#include "clad/Differentiator/Differentiator.h"
#include <iostream>

class Expression {
public:
  Expression(double p_x = 0, double p_y = 0) : x(p_x), y(p_y) {}
  double x, y;
  double g(double i) const {
    return (x + y) * i * i;
  }
};

int main() {
  const Expression expr_1(2, 3), expr_2(3, 3);
  auto d_g = clad::differentiate(&Expression::g, "i");
  std::cout << "d_g.execute(expr_1,2) = " << d_g.execute(expr_1, 2) << "\n";
  std::cout << "d_g.execute(expr_2,2) = " << d_g.execute(expr_2, 2) << "\n"; 
}
```

Error: 
```
const-memfn-example.cpp:15:14: error: no matching function for call to 'differentiate'
  auto d_g = clad::differentiate(&Expression::g, "i");
             ^~~~~~~~~~~~~~~~~~~
/home/parth/Programming/gsoc/clad-unmodified/inst/include/clad/Differentiator/Differentiator.h:141:3: note: candidate template ignored: could not match 'R (*)(Args...)' against 'double (Expression::*)(double) const'
  differentiate(R (*f)(Args...), ArgSpec args = "", const char* code = "") {
  ^
/home/parth/Programming/gsoc/clad-unmodified/inst/include/clad/Differentiator/Differentiator.h:148:3: note: candidate template ignored: could not match 'type-parameter-0-2 (type-parameter-0-4...)' against 'double (double) const'
  differentiate(R (C::*f)(Args...), ArgSpec args = "", const char* code = "") {
  ^
1 error generated.
The terminal process "/usr/bin/zsh '-c', '/usr/bin/clang++ -g -Xclang -add-plugin -Xclang clad -Xclang -load -Xclang /home/parth/Programming/gsoc/clad-unmodified/inst/lib/clad.so -I/home/parth/Programming/gsoc/clad-unmodified/inst/include -x c++ -std=c++11 const-memfn-example.cpp -o build/const-memfn-example && build/const-memfn-example'" terminated with exit code: 1.
```

One potential fix of this error is by modifying and specializing `FnTypeTrait` to determine if a function is constant member function at compile time . After implementing changes required for this potential fix, differentiation of both non-const member functions and const member functions are working correctly.

This potential fix involve making changes to following templates
- `FnTypeTrait`
- `CladFunction`

and all codes which use these templates.

Modifications to be done in `FnTypeTrait` for this potential fix.

``` c++
// Added isConstantMemFn non-type parameter to determine if the member function is constant at compile time
template<bool isMemFn,bool isConstantMemFn,typename ReturnResult, typename... ArgTypes>
  struct FnTypeTrait {
    using type = ReturnResult (*)(ArgTypes...);

    static ReturnResult execute(type f, ArgTypes&&... args) {
      return f(args...);
    }
  };

// template specialization to be used when both isMemFn and isConstantMemFn are true
  template<typename ReturnResult, class C, typename... ArgTypes>
  struct FnTypeTrait<true,true, ReturnResult, C, ArgTypes...> {
    using type = ReturnResult (C::*)(ArgTypes...) const; 

    static ReturnResult execute(type f, const C& self, ArgTypes&&... args) {
      // cast away the const and call.
      return (const_cast<C&>(self).*f)(args...);
    }
  };
```
Similarly changes will be needed in `CladFunction` template parameter list to pass `isConstantMemFn` to `FnTypeTrait`. Is this a good enough solution for this problem ? This potential fix do involve duplicating some code. Should I make a Pull Request with this fix ?

**Comment by vgvassilev** [comment]
Thanks for the report.

Go ahead and open a PR with the fix and a few regression tests. I'd very much avoid duplicating code.

**Comment by parth-07** [comment]
Will start working on this PR soon :) 
I have one doubt, I have to write regression tests for this bug, similar to the tests in `clad/tests` directory, right ?

**Comment by grimmmyshini** [comment]
@parth-07 

1) yes, I see you've already done that.

2) all that space would probably be llvm; but yes, it is normal.

**Comment by parth-07** [comment]
@grimmmyshini Yes, I studied test format from other tests in the repository and lit llvm documentation.
 And is there any additional benefit of using clang+llvm built standalone from source? For me, uptil now clang installed from package manager is working as good as the clang built from source. 

I also couldn't understand the meaning of `-lm`  flag used in run command in `/test/Arrays/Arrays.C`
`// RUN: %cladclang %s -lm -I%S/../../include -oArrays.out 2>&1 | FileCheck %s`.
I also tried searching abou this `-lm` flag online, but was not able to find any information about it.

**Comment by sudo-panda** [comment]
@parth-07 the `-lm` flag is used to link the math library. 

As for building clang from source, a few benefits it provides are:
- It spits out all the arguments that clang itself adds along with your own arguments so that you can find any side effects that can occur due to arguments that you haven't supplied
- It provides a stack dump at the point of failure which sometimes can help you determine the problem.

There may be more to this but these are the ones I have found till now.

**Comment by parth-07** [comment]
@sudo-panda thanks for the information :)

**Comment by vgvassilev** [comment]
@parth-07 thanks for the issue and the PR.

@pdimov and I were discussing how to avoid the multiple boolean flags in a possible implementation. It turns out we are missing support for `const, volatile, noexcept, &, &&`. We'd propose something like this https://godbolt.org/z/PvWeqG Can you adapt your PR to it and add tests for the various cases?

**Comment by parth-07** [comment]
Yes, I will adapt this method in the PR :) and add tests for the various cases.
Your proposed method solves the problem in a much better way.

**Comment by parth-07** [comment]
@vgvassilev @grimmmyshini 
For differentiation mode other then forward mode ( gradient, hessian and jacobian). There is still need of 2 overloaded methods, one for member functions and other non-member functions. Because to apply `reinterpret_cast`, we need function's parameter list type in the form of parameter pack, and I am unable to find a way to obtain function parameter list types with just function pointer. So I had to fall back to `R (*)(Args... args)` and `R(C::*)(Args.. args)` representations.

Please do suggest, if there's a better way such that both member and non-member functions can be accepted by the function without any overloading. Currently I am using definition of `clad::gradient` like this(I have handled hessian and jacobian in a similar way).

```c++
template<typename ArgSpec = const char *, typename R, typename... Args>
  CladFunction<void (*)(Args...,R*)> __attribute__((annotate("G")))
  gradient(R (*f)(Args...), ArgSpec args = "", const char* code = "") {
    assert(f && "Must pass in a non-0 argument");
    return CladFunction<void (*)(Args...,R*)>(
      reinterpret_cast<void (*) (Args..., R*)>(f) /* will be replaced by gradient*/,
      code);
  }

  template<typename ArgSpec = const char *, typename R,typename C, typename... Args>
  CladFunction<void (C::*)(Args...,R*)> __attribute__((annotate("G")))
  gradient(R (C::*f)(Args...), ArgSpec args = "", const char* code = "") {
    assert(f && "Must pass in a non-0 argument");
    return CladFunction<void (C::*)(Args...,R*)>(
      reinterpret_cast<void (C::*) (Args..., R*)>(f) /* will be replaced by gradient*/,
      code);
  }
```

and can I please rename template parameter `R` to `ReturnType` ? `ReturnType` seems more intuitive and relatively less ambigious.

And I have one more query, consider this case.

```c++
#include<iostream>
#include "clad/Differentiator/Differentiator.h"

struct Expression {
  Expression(double p_x=0,double p_y=0) : x(p_x) , y(p_y) {}
  double x,y;
  double f(double i) {
    return (x+y)*i*i;
  }
};

int main() {
  const Expression expr(2,3);
  auto d_f = clad::differentiate(&Expression::f);
  std::cout<<d_f.execute(2)<<"\n";
}
```
Now in this example, `Expression::f` is class non-const member function, thus derived function obtained is also non-const member function. 
And `expr` is `const Expression&` object, so by definition it cannot call non-const member function, thus it also cannot call derived function.
Is this the expected behaviour for this library, or should the user be able to call derived function even from the constant object as in this case ? Should it just be warning or straight out error ?

**Comment by parth-07** [comment]
Found a better way for `gradient, hessian and jacobian` functions, This method is similar to the method used for forward mode differentiation, and using this method only one function will be needed for both member and non-member function.

For this method, I am making a wrapper which can give the type of derived function, I will be making this wrapper(temporary name, will use more intuitive name in code) as follows: 

```c++
  template<class ReturnType>
  struct wrapper {};

  template<class T>
  using wrapper_t = typename wrapper<T>::type;

  template<class ReturnType,class... Args>
  struct wrapper<ReturnType (*)(Args...)> {
    using type = void (*)(Args...,ReturnType*);
  };

  template<class ReturnType, class C, class... Args>
  struct wrapper<ReturnType (C::*)(Args...)> {
    using type = void (C::*)(Args...,ReturnType*);
  };
```
Then using this wrapper structure, only one function will be needed for both member and non-member functions.
