### ISSUE TITLE
Differentiation of call expressions in reverse mode missisng cast

### ISSUE THREAD

**Issue by grimmmyshini** [vgvassilev/clad#214]
Minimal reproducible example:

```cpp
float helper (float a) {
    return a;
}

double fn (float a) {
    double x = helper(a);
    return x;
}

clad::gradient(fn);
```
results in 

```
void llvm::StoreInst::AssertOK(): Assertion `getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!"' failed.
```

The dump for ```fn``` reveals the following code...

```cpp
void fn_grad(float a, double *_result) {
    float _t0;
    double _d_x = 0;
    _t0 = a;
    double x = helper(_t0);
    double fn_return = x;
    goto _label0;
  _label0:
    _d_x += 1;
    {
        float _grad0[1] = {};
        helper_grad(_t0, _grad0);
        float _r0 = _d_x * _grad0[0UL];  //Line of interest, this fails but it actually should not
        _result[0UL] += _r0;
    }
}

```

Here, at the line of interest, we are possibly missing an implicit cast. 

@sudo-panda, this issue might be the core reason behind failure of ```pow``` in reverse mode. Maybe you would want to look into this and if possible, perhaps split your current PR (#206) to accommodate changes for both. 

Another thing to note is, this might not be the only place implicit casts are missing. So we should carefully find out such places and make sure the implicit casts are built.

**Comment by sudo-panda** [comment]
@grimmmyshini I will look into this

**Comment by parth-07** [comment]
In this specific example, what should be the differentiation of function `fn` wrt `a`, should it be 1 or 0 ? Ideally it should be `1`. But in clad built using clang installed from package manager,output of differentiation of `fn` wrt to `a`  is `0`

**Comment by grimmmyshini** [comment]
@parth-07 yes, that is a wrong result because this code should not even run (it does in the packet manager version because asserts are disabled hence the wrong result). When you fix the casting issue, the result is as expected; 1.

**Comment by sudo-panda** [comment]
I think one way this issue can be solved by using implicit cast. Snippet:

```
          auto di = BuildOp(BO_Mul, dfdx(), ithResult);

          // Since clang won't automatically promote di to the type of the variable
          // in which it is being store, we need to specify an implicit type cast
          // so that clang won't throw an error.
          Expr *cdi;
          if(di->getType()->isFloatingType() && CEType->isIntegerType()) {
            cdi = ImplicitCastExpr::Create(m_Context, CEType,
                                           CK_IntegralToFloating, di,
                                           nullptr, VK_RValue);
          } else if(di->getType()->isFloatingType() && CEType->isFloatingType()) {
            cdi = ImplicitCastExpr::Create(m_Context, CEType, CK_FloatingCast,
                                           di, nullptr, VK_RValue);
          } else if(di->getType()->isIntegerType() && CEType->isIntegerType()) {
            cdi = ImplicitCastExpr::Create(m_Context, CEType,
                                           CK_IntegralCast, di, nullptr,
                                           VK_RValue);
          } else {
            cdi = di;
          }

          ArgResultDecls[i]->setInit(cdi);
```

The rigidity of ImplicitCastExpr is the reason the code is messy. Also I am unsure of the type conversions we need to support in the above code and if the number of branches become too long I will try to convert it into a switch case.

**Comment by vgvassilev** [comment]
You should be able to set a breakpoint in clang and see which is the caller interface of `ImplicitCastExpr::Crete` -- there should be a function in `Sema` that does this for you (maybe `Sema::DefaultLvalueConversion`)?.

**Comment by sudo-panda** [comment]
@vgvassilev is the `Sema::PerformImplicitConversion` the function you are referring to?

**Comment by vgvassilev** [comment]
Yeah, that should be it.
