### ISSUE TITLE
Deciding the array size to be used when differentiating VisitCallExpr

### ISSUE THREAD

**Issue by sudo-panda** [vgvassilev/clad#242]
This issue references the PR #237 

We need to decide the size temporary array that is build for a `CallExpr`. For example, when the below function is differentiated:

```cpp
void f(double *a, double *out) {
  g(a, out);
}
```

The grad function is:

```cpp
f_grad(double *a, double *_d_a, double *out) {
    double *_t0;
    double *_t1;
    _t0 = a;
    _t1 = out;
    g(_t0, _t1);
    {
        double _grad0[10] = {};           // This is the array in consideration
        g_grad(_t0, _grad0, _t1);
        double *_r0 = _grad0;
        _d_a = _r0;
        double *_r1;
    }
}
```

The required size of _grad0 cannot be calculated before differentiating the g function so we need to decide between:

 -   Allowing users to set a size by using a macro or an argument
 -  Calculating the diff function and determining the size required before declaring the grad array (will take more computation)

**Comment by PetroZarytskyi** [comment]
This was fixed at some point. The gradient generated on the current master is:
```
void f_grad(double *a, double *out, clad::array_ref<double> _d_a, clad::array_ref<double> _d_out) {
    g(a, out);
    g_pullback(a, out, _d_a, _d_out);
}
```
We don't create ``_grad``/``_r`` variables for pointer arguments anymore. 
If somebody believes this is not the case, please reopen the issue.
