### ISSUE TITLE
Multiple pops to array index causes failed assertions in reverse mode 

### ISSUE THREAD

**Issue by grimmmyshini** [vgvassilev/clad#246]
Consider the following (dummy) example:

```cpp 
float func1(float x){
  float arr[10];
    for (int i = 0; i < 9; i++){
      arr[i] += x;
    }
  return arr[9];
}
```

The generated derivative of this in reverse mode is as follows: 

```cpp
void func1_grad(float x, float *_result) {
    float _d_arr[10] = {};
    unsigned long _t0;
    int _d_i = 0;
    clad::tape<int> _t1 = {};
    float arr[10];
    _t0 = 0;
    for (int i = 0; i < 9; i++) {
        _t0++;
        arr[clad::push(_t1, i)] += x;     <--  only one push of index per iteration
    }
    float func1_return = arr[9];
    goto _label0;
  _label0:
    _d_arr[9] += 1;
    for (; _t0; _t0--) {
        {
            float _r_d0 = _d_arr[clad::pop(_t1)];    <-- pop one
            _d_arr[clad::pop(_t1)] += _r_d0;          <-- pop two
            _result[0UL] += _r_d0;
            _d_arr[clad::pop(_t1)] -= _r_d0;           <-- pop three
        }
    }
}

```

Here, popping the index more than the number of times it was pushed causes a ```clad::tape_impl::reference clad::tape_impl<int>::back() [T = int]: Assertion `_size' failed.```

**Proposed solution(s):**

1. Replace ```clad::pop``` in the reverse block with ```clad::back```. The code will then look like so:

```cpp
{
       float _r_d0 = _d_arr[clad::back(_t1)];     <-- use back in expressions 
       _d_arr[clad::back(_t1)] += _r_d0;          
       _result[0UL] += _r_d0;
       _d_arr[clad::back(_t1)] -= _r_d0;           
       clad::pop(_t1);                                        <--finally pop here after use
}
```
This is a bit "harder" to develop in the sense that we would have to backpropagate 3 calls -- push, pop, and back. This would require either changing the structure of the ```VisitArraySubscriptExpr``` by some amount or developing a hacky fix to send the values back.

2. build a temporary replacement for the popped value

```cpp
{
       int _t0 = clad::pop(_t1);      <-- store pop value in expression
       float _r_d0 = _d_arr[_t0];     <-- use temp value here
       _d_arr[_t0]] += _r_d0;          
       _result[0UL] += _r_d0;
       _d_arr[_t0]] -= _r_d0;                                        
}
```
Easier to implement, no major change in the structure of ```VisitArraySubscriptExpr```. However, it introduces a new variable (although it is local) to the compound statement scope. 

Any ideas on which one would be better? Or any other better suggestions?

Once a proposed solution is decided, I would like to put in a PR for this!

**Comment by vgvassilev** [comment]
Thanks for the differential diagnosis on that!

I have no strong preference; maybe leaning towards `2.`. I am not sure if that direction won't break some assumptions. For example, did the tape design assumed `push` and `pop` to be balanced for the sake of consistent replays? I bet @efremale is the better source of knowledge.

**Comment by grimmmyshini** [comment]
It seems to me that was the case, the tape is pushed/popped from very optimistically. There is no further checking than the bounds. Also, even if any such assumptions were made, we can easily obey them. For solution 2, we would be making changes like so in ```ReverseModeVisitor::VisitArraySubscriptExpr```:

```cpp
for (std::size_t i = 0; i < Indices.size(); i++) {
      StmtDiff IdxDiff = Visit(Indices[i]);
      StmtDiff IdxStored = GlobalStoreAndRef(IdxDiff.getExpr());
      if (isInsideLoop) {
        // Here we make sure that we are popping each time we push
        // Since the max no of pushes = no. of array index expressions in the loop 
        Expr* popVal = StoreAndRef(IdxStored.getExpr_dx(), reverse);
        IdxStored = StmtDiff(IdxStored.getExpr(), popVal);
      }
      clonedIndices[i] = IdxStored.getExpr();
      reverseIndices[i] = IdxStored.getExpr_dx();
    }
```

So taking two cases:

```cpp 
for (int i = 0; i < 10; i++){
  arr[i]  += x;  // Here only one push happens
}
```

and the first case is the same as above but it uses the add operator

```cpp 
for (int i = 0; i < 10; i++){
  arr[i]  = arr[i] + x;  // Here two pushes of the same index happen
}
```
Now of course there will be two variables having the same value for the above case, but to avoid this we might have to do more complex checks.

IMO, the suggested changes will take care of both of the cases. However, this might not be the best way? Not sure. Maybe @efremale can give some inputs on this.
