### ISSUE TITLE
Differentiation fails if function is defined after the call to clad differentiation functions.

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#248]
Currently, differentiation fails if the function to differentiate is defined after the call to clad differentiation functions. For example, 

```c++
#include <iostream>
#include "clad/Differentiator/Differentiator.h"

double fn(double, double);

int main() {
  auto d_fn = clad::differentiate(fn, "i");
  std::cout<<d_fn.execute(3, 5);
}

double fn(double i, double j) {
  return i*i*j;
}
```

This code gives error: **attempted differentiation of function 'fn', which does not have a definition**

The cause of the problem here is, clang is unaware of `fn` definition when `DerivativeBuilder::Derive` is called to differentiate fn and we need the function body to differentiate it.

**Comment by grimmmyshini** [comment]
For this issue, we might want to use ```getDefinition()``` here 

_DiffPlanner.cpp line 258_
```cpp
auto derivedFD = cast<FunctionDecl>(DRE->getDecl());
request.Function = derivedFD;
```
rather than ```getDecl()```. Although, not entirely sure if just changing this works.

**Comment by parth-07** [comment]
Sorry for the late reply. 

`getDefinition` will likely not help here, since we are already using `getDefinition` in [`DerivativeBuilder::Derive`](https://github.com/vgvassilev/clad/blob/031db32ce4a03f15b0621618187a4411b5340be3/lib/Differentiator/DerivativeBuilder.cpp#L113) before differentiating functions. 

The cause of the problem seems to be that the function body has not been parsed at the time when we are trying to differentiate the function.

**Comment by grimmmyshini** [comment]
Ah, well then we can't really fix this unless the gradient generation is deferred to after the whole code has been parsed, which I am not sure of the feasibility of...
