### ISSUE TITLE
[Feature Request] Add a generic interface to support plugins in clad.

### ISSUE THREAD

**Issue by grimmmyshini** [vgvassilev/clad#257]
It might be useful to employ a callback-based approach to implement a generic interface that all plugins to clad can implement, this will maintain uniformity and ensure that access rights are not being misused. This may be implemented as an abstract class that can be extended by the specific plugin.

How we would go about implementing this is having well-defined "hooks" or "events" that would trigger a call to one of the functions in our callback interface. An example of an event in clad may be after calculating the derivative of a ```BinOp``` expression (or other similar events that can be clearly identified in the code).

[Inspiration from clang PPCallbacks](https://clang.llvm.org/doxygen/classclang_1_1PPCallbacks.html).

**Comment by vgvassilev** [comment]
Resolved by #304.
