### ISSUE TITLE
Remove extra statement during gradient generation

### ISSUE THREAD

**Issue by sudo-panda** [vgvassilev/clad#274]
Sample source code:
```c++
double f(double x, double y) {
  y = x;
  return y;
}
```
Diff generated:
```c++
void f_grad(double x, double y, clad::array_ref<double> _d_x, clad::array_ref<double> _d_y) {
    y = x;
    double f_return = y;
    goto _label0;
  _label0:
    * _d_y += 1;
    {
        double _r_d0 = * _d_y;
        * _d_x += _r_d0;
        * _d_y -= _r_d0;
        * _d_y;      // <- Extra statement
    }
}
```
This is because clang thinks the result is not unused (`_d_y` is of `clad::array_ref` type and `* _d_y` calls an operator overload of `clad::array_ref` so clang is not wrong in assuming that). This makes the condition [isUnusedResult](https://github.com/vgvassilev/clad/blob/b09c8dfcd12fa6286607f9d07f037225da11103f/lib/Differentiator/VisitorBase.cpp#L177) be `false`. 

One of the solutions would be to add a condition in [isUnusedResult](https://github.com/vgvassilev/clad/blob/b09c8dfcd12fa6286607f9d07f037225da11103f/lib/Differentiator/VisitorBase.cpp#L165-L171) function to check if the variable is of the type `clad::array_ref` and the only operation being carried out is a dereference operation.

**Comment by vgvassilev** [comment]
This issue will be potentially fixed by addressing #726.

**Comment by vgvassilev** [comment]
@PetroZarytskyi, can we close this issue now?

**Comment by vgvassilev** [comment]
This issue seems fixed by the recent PRs.
