### ISSUE TITLE
Compiling clad should support -j

### ISSUE THREAD

**Issue by davidlange6** [vgvassilev/clad#322]
As who has time to compile clang+clad with one core?

Following

https://github.com/vgvassilev/clad#building-from-source-llvm-clang-and-clad-development-environment

but with -j <N> , where N>1, results in errors such as

```
src/tools/clad/../clang/include/clang/AST/ASTFwd.h:21:10: fatal error: clang/AST/DeclNodes.inc: No such file or directory
   21 | #include "clang/AST/DeclNodes.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
```

which will go away after compiling enough times.. Presumably a missing dependency?

**Comment by vgvassilev** [comment]
Should be resolved by PR #331
