### ISSUE TITLE
Readability suggestion

### ISSUE THREAD

**Issue by davidlange6** [vgvassilev/clad#377]
https://github.com/vgvassilev/clad/blob/4f1c10e7d9237d4929822fa6e1074dfe377e4ec6/include/clad/Differentiator/Differentiator.h#L201

would be more readable with another line break

```
printf("The code is: \n%s\n", getCode());
```

**Comment by davidlange6** [comment]
(or maybe even just drop The code is and let the user add that if they want)

**Comment by vgvassilev** [comment]
The getCode interface seems to be doing what you have in mind. Is it missing something?

**Comment by davidlange6** [comment]
Yes, at the minimum, a line break so that the code starts on column one.

**Comment by vgvassilev** [comment]
@Nirhar, can you look into this issue, too?
