### ISSUE TITLE
Improve consistency of `GlobalStoreAndRef`

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#431]
`GlobalStoreAndRef` creates a variable that can be used for storing and accessing information in the global scope of the function. 
It internally uses `clad::tape`, if and only if, it needs to store the value of an expression contained with a loop. 
A close cousin of `GlobalStoreAndRef` is `StoreAndRef` -- it creates a variable that can be used for storing and accessing information in the local scope. 

`GlobalStoreAndRef` returns a `StmtDiff` object containing expressions that should be used in the forward pass and the reverse pass respectively. 

If `GlobalStoreAndRef` is used to store an expression that is not contained within a loop, then it returns `{ref, ref}`, where `ref` is a `DeclRefExpr` node for the global variable created by `GlobalStoreAndRef`. Please note the following things:

- `ref` can be used any number of times in the generated function. 
- The interface of `StoreAndRef` is consistent with `StoreAndRef` -- increased consistency makes is easier to reason about the behaviour of a program.

If `GlobalStoreAndRef` is used to store an expression that is contained within a loop, then in returns `{clad::push(...), clad::pop(...)}`. Please note the following things: 

- `clad::push` and `clad::pop` should ideally be used once only, or more precisely, they should be used exactly same number of times in the forward and the reverse pass. This doesn't always match with the differentiation requirements.
- The interface is different for the special case in which the stored expression resides in a loop. This creates difficulties in the cases where we need to be agnostic about if the expression is contained in a loop or not. For these cases, currently, we need to have separate branches such as these: 

```cpp
if (isInsideLoop) {
  ...
  ...
} else {
  ...
  ...
}
```
It also makes `GlobalStoreAndRef` behaviour inconsistent, and forces the developer using this functionality to be extra cautious. 

I propose to make the functionality `GlobalStoreAndRef` more consistent and easier to use. If `GlobalStoreAndRef` is used to store an expression that is contained in a loop. Then we can modify `GlobalStoreAndRef` to behave as follows: 

```cpp
// global variable declarations
clad::tape<double> t0;

// forward pass
for (...; ...; ...) {
  double t1 = t0.push(e);  // added implicitly by 'GlobalStoreAndRef' in the current forward block
  ....
}

// reverse pass
for (...; ...; ...) {
  double t2 = t0.pop();  // added implicitly by 'GlobalStoreAndRef' in the current reverse block
}
```

Now, `GlobalStoreAndRef` will return `{t1, t2}`. 

This can help to simplify various implementation that uses `GlobalStoreAndRef`, most notably -- `ReverseModeVisitor::VisitCallExpr`. 

This functionality have a downside that it creates 2 additional variables, thus if we do decide to add this functionality, we should add some flag in `GlobalStoreAndRef` function using which developer that needs to use `GlobalStoreAndRef` functionality can optimally decide if they require this additional consistency or not.

**Comment by vgvassilev** [comment]
This approach would make sense to me. In a first approximation we should fix the consistency problem - I think the temporary variables will be optimized by the compiler optimizer.
