### ISSUE TITLE
Add tests for differentiation of `constexpr` and `consteval` functions 

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#437]
Differentiation of `constexpr` and `consteval` functions should produce `constexpr` and `consteval` functions respectively. Clad supports differentiation of `constexpr` and `consteval` functions with this expected behaviour, but we currently do not have any test for it.

**Comment by Nirhar** [comment]
I'm planning to add a file called "ConstFunctions.C" in the each of the folders ForwardMode, Gradient, Hessian and Jacobian (in the test folder) to test constexpr and consteval function differentiation in these 4 modes. Is this fine @parth-07 @vgvassilev  ?

**Comment by vgvassilev** [comment]
Yeah, that makes sense to me.

**Comment by parth-07** [comment]
> Is this fine?

Yes, definitely. Feel free to ping here if you face any issues while adding test for these functions.
