### ISSUE TITLE
`VisitorBase::Clone` does not handle declaration replacement

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#439]
We often use the `VisitorBase::Clone` function in all the `Visitor` classes to perform cloning of the original expression. This is mostly used for the cases where we do not need the derivative of primal expression, as in those cases, we use `Visit(...)` function instead.

`VisitorBase::Clone` function does not handle declaration replacement, and can thus produce incorrect cloned expressions. In all the `Visitor` classes, declaration replacement is being handled in `VisitDeclRefExpr`. Therefore, currently,  the only way to get correct cloned expression in all cases is using `Visit` function.

**Comment by ro4i7** [comment]
Hello @parth-07 @vgvassilev 

To solve this issue, you can modify the `VisitorBase::Clone` function to handle declaration replacement by calling the `VisitDeclRefExpr` function for each `DeclRefExpr` encountered during the cloning process. Here is an example implementation:
```
clang::Expr* VisitorBase::Clone(const clang::Expr* E) {
  // Create a new expression of the same type as the original.
  clang::Expr* NewExpr = E->Clone(context);
  // Replace declarations in the cloned expression.
  ReplaceDecls(NewExpr);
  return NewExpr;
}

void VisitorBase::ReplaceDecls(clang::Expr* E) {
  if (!E) return;
  switch (E->getStmtClass()) {
    case clang::Stmt::DeclRefExprClass: {
      clang::DeclRefExpr* DRE = llvm::cast<clang::DeclRefExpr>(E);
      clang::ValueDecl* VD = DRE->getDecl();
      if (clang::VarDecl* Var = llvm::dyn_cast<clang::VarDecl>(VD)) {
        if (Var->hasInit()) {
          // Recursively clone the initializer expression.
          clang::Expr* Init = Clone(Var->getInit());
          // Replace the initializer in the cloned expression.
          Var->setInit(Init);
        }
      }
      break;
    }
    default:
      // Recursively replace declarations in child expressions.
      for (auto& Child : E->children()) {
        ReplaceDecls(Child);
      }
      break;
  }
}
```
This implementation uses a `ReplaceDecls` function to recursively replace declarations in the cloned expression. It checks each `DeclRefExpr` encountered during the cloning process and calls `Clone `on the initializer expression if it exists. Then, it replaces the initializer in the cloned expression. Finally, it recursively replaces declarations in child expressions.

With this modification, you should be able to use `VisitorBase::Clone` to correctly clone expressions with declaration replacement in all cases.

**Comment by vgvassilev** [comment]
@ro4i7, please stop commenting under every issue. Select one or two issues and work to solve them, then repeat.
