### ISSUE TITLE
[ci] Add a clang/libc++ builders for unix

### ISSUE THREAD

**Issue by vgvassilev** [vgvassilev/clad#444]

**Comment by ro4i7** [comment]
Hello @parth-07 @vgvassilev 

To build script for a Unix-based system using Clang and libc++:
```
#!/bin/bash
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
export CXXFLAGS="-stdlib=libc++"
mkdir build && cd build
cmake ..
make -j4
```
This script sets the environment variables for the Clang compiler and the C++ standard library to be used during the build process. It then creates a build directory, runs CMake to configure the project, and builds the project using the make command with 4 parallel jobs.

Once the build script is set up, then configure our CI tool to execute this script on the virtual machine for each new commit or pull request. This will ensure that the project is continuously built and tested with the Clang compiler and libc++ library on a Unix system.

**Comment by vgvassilev** [comment]
@mcbarton, do you mind looking into this?

**Comment by mcbarton** [comment]
@vgvassilev yes, I can look into this for you.

**Comment by vgvassilev** [comment]
> @vgvassilev yes, I can look into this for you.

Thank you. I figured would be probably a quick fix since you dug in that area recently..

**Comment by mcbarton** [comment]
Closing as a result of the outcome of the debugging showing conflicting standard libraries trying to be used (see https://github.com/vgvassilev/clad/pull/850#issuecomment-2067596340 for more details).

@vgvassilev can you close this issue?

**Comment by vgvassilev** [comment]
Yes, closing.
