### ISSUE TITLE
Add an option to specify independent variables for gradients

### ISSUE THREAD

**Issue by efremale** [vgvassilev/clad#46]
Now we can only compute gradients w.r.t. to every argument of a function.

For efficiency reasons, it seems to be a good idea to be able to specify indices required of independent variables, e.g.:

```
clad::gradient(f, 0, 2, 4)
```
or
```
clad::gradient(f, {0, 2, 4})
```
or even
```
clad::gradient(f, std::index_sequence<0, 2, 4>{})
```

**Comment by vaithak** [comment]
This seems to be already supported. We can close this.
cc: @vgvassilev

**Comment by vaithak** [comment]
Clad currently supports adding the name of the independent variables to specify the gradient computation.
For ex.: `clad::gradient(fn, "x, y")`;
Do we want to support specifying indices too?

**Comment by vgvassilev** [comment]
I am not sure, however, we support indices in forward mode…

**Comment by PetroZarytskyi** [comment]
@vgvassilev I think we already support indices in the reverse mode. I just tested. Do we want anything else?

**Comment by vgvassilev** [comment]
Can we update the documentation and the readme examples first?
