### ISSUE TITLE
Array arguments does not works => (error: no viable conversion from 'const float *' to 'clad::array_ref<float>')

### ISSUE THREAD

**Issue by FROL256** [vgvassilev/clad#468]
```cpp
static inline float EvalGGX(float l[3], float v[3], float n[3], float roughness)
{
 ...
}
```
Full code is available here https://github.com/FROL256/clad_autodiff_examples/blob/main/SourceFile.cpp 

This example previously (~6 mouth ago) worked fine for me (https://github.com/FROL256/clad_autodiff_examples/blob/main/Derivatives.cpp) 

It seems it is broken recently, will try several previous release.

**Comment by FROL256** [comment]
Release version v0.9 works fine. Probably this is an issue for current version in master branch

**Comment by parth-07** [comment]
Thank you for creating the issue.

In the full code, you have: 

```cpp
auto ggx_grad = clad::gradient(EvalGGX);
...
float result1[10] = {};
ggx_grad.execute(lightDir.M, viewDir.M, normal.M, roughness, 
                   &result1[0], &result1[3], &result1[6], &result1[9]);
...

Here one issue is that the clad expects the derivative argument of array arguments to be of type `clad::array_ref`. `clad::array_ref` takes the derivative array base address and size in its constructor call. And yes, this is a recent change. 

Please try this modified code with the master version of clad:
```cpp
auto ggx_grad = clad::gradient(EvalGGX);
...
float result1[10] = {};
clad::array_ref<float> dl_ref(&result1, 3);
clad::array_ref<float> dv_ref(&result1 + 3, 3);
clad::array_ref<float> dn_ref(&result1 + 6, 3);
ggx_grad.execute(lightDir.M, viewDir.M, normal.M, roughness, 
                   dl_ref, dv_ref, ,dn_ref &result1[9]);

```

Please do update us if this do not work or if you face any other issue while using Clad.

**Comment by FROL256** [comment]
Thank you very much! I have found similar issue in other example. 
Replacing pointers to clad::array_ref with known size worked for me!

Well, anyway could you please clarify this issue. This update confuses me a little and makes me worried about performance. Please correct me if I'm wrong, but previously we had fixed array size and code like this

```cpp
        float _r12 = _d_dotNH * _t14;
        _d_n[0] += _r12;
        float _r13 = _t15 * _d_dotNH;
        _d_h[0] += _r13;
        float _r14 = _d_dotNH * _t16;
        _d_n[1] += _r14;
        float _r15 = _t17 * _d_dotNH;
        _d_h[1] += _r15;
        float _r16 = _d_dotNH * _t18;
        _d_n[2] += _r16;
        float _r17 = _t19 * _d_dotNH;
        _d_h[2] += _r17;
```
i.e. for fixed array size we had fully unrolled code for gradients computation with is absolutely perfect for GLSL compiler, for example. And actually i have same code for my example with EvalGGX currently, well, ok. 

But ... in my another example i have different kind of code

```cpp
{
        clad::array<float> _grad0(_d_B.size());
        clad::array<float> _grad1(_d_V.size());
        ProjectX_grad(_t0, _t1, _grad0, _grad1);
        clad::array_ref<float> _r0(_grad0 *= _d_xNDC);
        _d_B += _r0;
        clad::array_ref<float> _r1(_grad1 *= _d_xNDC);
        _d_V += _r1;
    }
```


So, we do know array size, but don't use it ... don't unroll the code which is definitely bad for my case when i have small arrays for most of arguments (usually 3-4, rarely 8 or 16). AFAIK, even for CUDA such code will work bad forcing put all such variables in global memory. 

So ... is there a way to avoid such constructs in the generated code? I don't understand the conditions when this happens.
The input is:

```cpp
float ProjectX(float B[16], float V[4])
{
  float W = V[0] * B[3] + V[1] * B[7] + V[2] * B[11] + V[3] * B[15]; 
  return V[0]/W;
}

float NdcToScreenSpace(float x, float width)
{
  return (x*0.5f + 0.5f)*width - 0.5f;
}

float VS_X(float B[16], float V[4], float width)
{
  const float xNDC = ProjectX(B,V);
  return NdcToScreenSpace(xNDC, width);
}
```

Thank you very much!

**Comment by parth-07** [comment]
Thank you very much for the questions and insights! 

> This update confuses me a little 

I agree this update is confusing.  The size of a derivative of an array was required to be known to the derivative function for properly differentiating function calls. There will be updates to improve this design and reduce the dependency on array size where possible. 

> and makes me worried about performance. 

I will try my best to address the performance concerns you have mentioned. 

> but previously we had fixed array size and code like this

```cpp
        float _r12 = _d_dotNH * _t14;
        _d_n[0] += _r12;
        float _r13 = _t15 * _d_dotNH;
        _d_h[0] += _r13;
        float _r14 = _d_dotNH * _t16;
        _d_n[1] += _r14;
        float _r15 = _t17 * _d_dotNH;
        _d_h[1] += _r15;
        float _r16 = _d_dotNH * _t18;
        _d_n[2] += _r16;
        float _r17 = _t19 * _d_dotNH;
        _d_h[2] += _r17;
```

If `d_n` and `d_h` are derivatives of array parameters, then even previously, `_d_n`, and `_d_h`, were just pointers -- not arrays. Thus the derivative function did not have any size information about the derivatives of array parameters. 

Can you please add the original statement, from which we can obtain this transformation? I would like to provide an intuition for the changes in the derived code generated by previous versions of Clad and with the current version of Clad.

```cpp
{
        clad::array<float> _grad0(_d_B.size());
        clad::array<float> _grad1(_d_V.size());
        ProjectX_grad(_t0, _t1, _grad0, _grad1);
        clad::array_ref<float> _r0(_grad0 *= _d_xNDC);
        _d_B += _r0;
        clad::array_ref<float> _r1(_grad1 *= _d_xNDC);
        _d_V += _r1;
    }
```

The current version of Clad should not generate this code. Can you please provide the original statement from which we can obtain this transformation?

> So, we do know array size, but don't use it ... don't unroll the code which is definitely bad for my case when I have small arrays for most of the arguments (usually 3-4, rarely 8 or 16). AFAIK, even for CUDA such code will work bad forcing put all such variables in global memory.

We still do loop unrolling at the places where we did it before. In the particular case of differentiating function calls that you have mentioned, we have modified the design such that we do not need to create temporary `_grad` arrays and thus there are no operations such as:

```cpp
d_arr += _grad0;
```

For a concrete example, please consider this function call:

```cpp
projectX(B, V);
```

The corresponding derived code will be as follows:

```cpp
// forward pass
projectX(B, V);

// reverse pass
projectX_pullback(B, V, _d_B, _d_V);
```

That's it. There are no `_grad` variables involved now. This transformation example assumes that `B` and `V` are not modified by the function `projectX`. If they were modified then we need to perform cloning of `B` and `V` as well. 

> So ... is there a way to avoid such constructs in the generated code? I don't understand the conditions when this happens.

Please provide the original statements of the differentiated codes that you have provided. I want to understand the problem in more detail. 

Thank you very much for your questions.

**Comment by FROL256** [comment]
I made a specific branch for this issue (called 'project'): https://github.com/FROL256/clad_autodiff_examples/tree/project

There is 2 versions of 'VS_X' function. The first one calls other functions (ProjectX and NdcToScreenSpace). 
And the second one is fully in-lined (commented in the source file).

The first version (with calls) produces undesired code:
https://github.com/FROL256/clad_autodiff_examples/blob/project/Derivatives.cpp (at the end of the file) 

And the second one (in-lined) is not. Well, particularly for me this is ok, think i can inline the code and be happy )

**Comment by parth-07** [comment]
Thank you very much for the code links. 
I will examine them, and try my best to address the concerns that you mentioned. I will need some time for this.

> Well, particularly for me this is ok, think I can inline the code and be happy

Please don't settle for less. Clad is under active development, and we would be happy to add/improve any feature that users find important.

**Comment by vgvassilev** [comment]
@FROL256, I think the `clad::array`/`clad::array_ref` change intended to introduce a zero-cost abstraction which was capable of carrying array size information throughout the differentiation process. In mid term I think we have found a better approach to use less of `array_ref` in our code (as discussed by @parth-07)

Do I understand correctly that GLSL has problems optimizing the code when seeing an `array_ref`?

**Comment by parth-07** [comment]
> The first version (with calls) produces undesired code:
https://github.com/FROL256/clad_autodiff_examples/blob/project/Derivatives.cpp (at the end of the file)

To differentiate the function call:
```cpp
const float xNDC = ProjectX(_t0, _t1);
```

The first version produces:

```cpp
{
  clad::array<float> _grad0(_d_B.size());
  clad::array<float> _grad1(_d_V.size());
  ProjectX_grad(_t0, _t1, _grad0, _grad1);
  clad::array_ref<float> _r0(_grad0 *= _d_xNDC);
  _d_B += _r0;
  clad::array_ref<float> _r1(_grad1 *= _d_xNDC);
  _d_V += _r1;
}
```

It is more expensive than when you inline the function calls manually because it creates `_grad` variables to store temporary gradient results, and add statements to accumulate the temporary gradient results such as:

```cpp
// _d_B and _r0 are `clad::array_ref` objects;
// Underlying arrays of '_d_B' and '_r0' are of the same size. 
// '+=' have complexity equal to the size of the underlying arrays.
_d_B += _r0;
```

and 
```cpp
_d_V += _r1;
```

If you would use the latest Clad version, then the same function call,

```cpp
const float xNDC = ProjectX(_t0, _t1);
```

would produce the following adjoint statements:

```cpp
Project_pullback(B, V, _d_xNDC, _d_B, _d_V);
```

@FROL256 Would this code have any optimization issues for the GLSL compiler? Is the code undesirable for the GLSL compiler? 

It does not create any temporary gradient results like the earlier version of Clad did. And moreover, if the function `Project` is specified as `inline`, then `Project_pullback` will be an `inline` function as well. And thus, for functions that can be inlined by compilers, performance would be the same as manually inlining the function.

**Comment by FROL256** [comment]
>>Do I understand correctly that GLSL has problems optimizing the code when seeing an array_ref?
>>@FROL256 Would this code have any optimization issues for the GLSL compiler? Is the code undesirable for the GLSL compiler?

Well, hard question:

1. Most GPU compilers (include GLSL, OpenCL C) don't support C++ features at this level at all (classes, overloading operarors and e.t.c).
   So, if i had this zero-cost abstraction in the generated code, i have to change to some-thing else (right now just by hands).
   As i already said, it is not problem for me because i can make fully inlined version which works as expected.

2. Today we have qute heavy stack of technologies for GPU compilers and performance greately on many things (GLSL/C++ to SPIR-V, SPIR-V optimizer, SPIR-V to machine code).
   So, generally speak, i don't know ) 

3. From my experience, they are not so smart as clang or gcc; works pretty good with heavy math expressions, but have issues with variables which can not be allocated on stack with static address and thus can not be assigned to registers directly. In this case performance may degrade. 

4. So, what i'm trying to say, is that if you can keep generated code simply stupid, this is great, because i don't have to think -- whether my compliler optimize this zero-cost abstraction or not. I know that for fixed size arrays and variables we don't have issues usually and compiler do the best. 
   

>>If you would use the latest Clad version, then the same function call ... And thus, for functions that can be inlined by compilers, performance would be the same as manually inlining the function.

3. Ok, thats true. I think performance is ok even for v0.9.
   I have made a commit to the same branch where i have checked 2 versions of gradients.
   Indeed, the minimum execution time is the same for both versions (on CPU), so i think clang did a good optimization job.

Thank you for the detailed answer!
