### ISSUE TITLE
Reduce cloning complexity in forward mode

### ISSUE THREAD

**Issue by efremale** [vgvassilev/clad#47]
Each call to Clone() has complexity of O(n), where n is the size of the Stmt's subtree, since it recursively calls Clone() on every substatement until leaves are reached.

When differentiating a function via Forward/ReverseModeVisitor, we potentially call Clone() on every node of the AST tree (which recursively clones all subnodes, we are cloning same nodes multiple times) and have the total complexity of O(n^2).

Wouldn't it be more efficient to Clone() the whole tree just once before calling Visit() on it? The complexity should be just 2xO(n).

**Comment by vgvassilev** [comment]
@efremale can we now close this?

**Comment by efremale** [comment]
> @efremale can we now close this?

I believe some work is still required in the reverse mode.

**Comment by vgvassilev** [comment]
Ok, that's #94.
