### ISSUE TITLE
Incorrect Values for Gradient of a Function whose parameters are used in loop conditions

### ISSUE THREAD

**Issue by Nirhar** [vgvassilev/clad#474]
Here is the function:
```cpp
double x2_integral(double lower, double upper){
    double sum=0;
    double interval = 0.001;
    for(double x=lower;x<=upper;x+=interval){
        sum+=x*x*interval;
    }
    return sum;
}
```
Here is the code to differentiate it:
```cpp
auto grad=clad::gradient(x2_integral);
double x=1.0, y=2.0;
double dx,dy;
grad.execute(x,y, &dx, &dy);
printf("d_x = %.2f, d_y = %.2f\n", dx, dy);
```
Output of the above code snippet is: `d_x = 0.00, d_y = 0.00`, which is wong

Here is the derivative function generated:
```cpp
void x2_integral_grad(double lower, double upper, clad::array_ref<double> _d_lower, clad::array_ref<double> _d_upper) {
    double _d_sum = 0;
    double _d_interval = 0;
    unsigned long _t0;
    double _d_x = 0;
    clad::tape<double> _t1 = {};
    clad::tape<double> _t2 = {};
    clad::tape<double> _t3 = {};
    clad::tape<double> _t4 = {};
    double sum = 0;
    double interval = 0.001;
    _t0 = 0;
    for (double x = lower; x <= upper; x += interval) {
        _t0++;
        sum += clad::push(_t4, clad::push(_t3, x) * clad::push(_t2, x)) * clad::push(_t1, interval);
    }
    double x2_integral_return = sum;
    goto _label0;
  _label0:
    _d_sum += 1;
    for (; _t0; _t0--) {
        {
            double _r_d0 = _d_x;
            _d_x += _r_d0;
            _d_interval += _r_d0;
            _d_x -= _r_d0;
        }
        {
            {
                double _r_d1 = _d_sum;
                _d_sum += _r_d1;
                double _r0 = _r_d1 * clad::pop(_t1);
                double _r1 = _r0 * clad::pop(_t2);
                _d_x += _r1;
                double _r2 = clad::pop(_t3) * _r0;
                _d_x += _r2;
                double _r3 = clad::pop(_t4) * _r_d1;
                _d_interval += _r3;
                _d_sum -= _r_d1;
            }
        }
    }
}
```

**Comment by vaithak** [comment]
Hi, I am new to this repo and was just exploring the code and trying to pick up some good first issues to work on and found this to be an interesting one to work on. 

The forward mode gave the gradient as $\[3, 0\]$, so you are right the reverse mode is giving an inaccurate answer, but if I am not wrong, theoretically the aim is to calculate the gradient of the following function:

$$ f(a, b) =  \int_{a}^{b} x^2  \Rightarrow \nabla f = \[-a^2, b^2\]$$

So, the forward mode is also giving a theoretically incorrect result, I think that to achieve the theoretical result in the program, the interval should be dependent on lower and upper limits, so I modified the function as follows:
```cpp
double x2_integral(double lower, double upper)
{
    double sum = 0;
    double num_points = 10000;
    double interval = (upper - lower) / num_points;
    for (double x = lower; x <= upper; x += interval)
    {
        sum += x * x * interval;
    }
    return sum;
}
```

Now, the forward mode gives the theoretically correct result as $\[-1, 4\]$, but the reverse mode gives $\[-4, 4\]$, so yes there is some issue in the reverse mode which needs to be fixed.

For working on this, I have already explored about basics of clang plugins and llvm, just want to know if I should explore something specific in the code for fixing this or any other inputs that might help me.
Thanks :)

**Comment by vgvassilev** [comment]
> Hi, I am new to this repo and was just exploring the code and trying to pick up some good first issues to work on and found this to be an interesting one to work on.
> 
> The forward mode gave the gradient as [3,0], so you are right the reverse mode is giving an inaccurate answer, but if I am not wrong, theoretically the aim is to calculate the gradient of the following function:
> 
> f(a,b)=∫abx2⇒∇f=[−a2,b2]
> 
> So, the forward mode is also giving a theoretically incorrect result, I think that to achieve the theoretical result in the program, the interval should be dependent on lower and upper limits, so I modified the function as follows:
> 
> ```c++
> double x2_integral(double lower, double upper)
> {
>     double sum = 0;
>     double num_points = 10000;
>     double interval = (upper - lower) / num_points;
>     for (double x = lower; x <= upper; x += interval)
>     {
>         sum += x * x * interval;
>     }
>     return sum;
> }
> ```
> 
> Now, the forward mode gives the theoretically correct result as [−1,4], but the reverse mode gives [−4,4], so yes there is some issue in the reverse mode which needs to be fixed.
> 
> For working on this, I have already explored about basics of clang plugins and llvm, I am currently deep diving into the code, just want to know if I should explore something specific in the code for fixing this or any other inputs that might help me. Thanks :)

Hi @vaithak, this is a very detailed analysis of the issue. Thank you and welcome to the project! I am not aware of anybody else working on this issue.

I think the best way to move forward is to find where the emitted gradient code from reverse mode is broken. Once you that figure out it should be easy to find how to fix it to make the small program work. Then, you could find where Clad does not generate what's needed and propose a fix. Does that make sense?

**Comment by vaithak** [comment]
Thanks for replying @vgvassilev, yup that makes sense. 

I have found where the omitted code for reverse mode is broken, sharing here to provide visibility and in case someone wants to provide some suggestions. 

- By inspection, we can see that in both cases (the original function and the modified function to get theoretically correct result) the reverse mode is giving incorrect results for the first argument only and this is the one that is used during the initialization of for loop. 

- In our code, initialisation looks like this,
  ```c++
  double x2_integral(double lower, double upper)
  {
      ...
      for (double x = lower; ...)
      ...
  }
  ```  

- While doing a reverse-mode AD, the code should be doing `d_lower += dx` in the end somewhere for this and turns out this is what is missing from the generated code for the gradient. So, the gradient code should be somewhat modified like this:
```c++
  void custom_x2_integral_grad(double lower, double upper, clad::array_ref<double> _d_lower, clad::array_ref<double> _d_upper)
  {
      double _d_sum = 0;
      double _d_num_points = 0;
      double _t0;
      double _t1;
      double _d_interval = 0;
      unsigned long _t2;
      double _d_x = 0;
      clad::tape<double> _t3 = {};
      clad::tape<double> _t4 = {};
      clad::tape<double> _t5 = {};
      clad::tape<double> _t6 = {};
      double sum = 0;
      double num_points = 10000;
      _t1 = (upper - lower);
      _t0 = num_points;
      double interval = _t1 / _t0;
      _t2 = 0;
      for (double x = lower; x <= upper; x += interval)
      {
          _t2++;
          sum += clad::push(_t6, clad::push(_t5, x) * clad::push(_t4, x)) * clad::push(_t3, interval);
      }
      double x2_integral_return = sum;
      goto _label0;
  _label0:
      _d_sum += 1;
      for (; _t2; _t2--)
      {
          {
              double _r_d0 = _d_x;
              _d_x += _r_d0;
              _d_interval += _r_d0;
              _d_x -= _r_d0;
          }
          {
              {
                  double _r_d1 = _d_sum;
                  _d_sum += _r_d1;
                  double _r2 = _r_d1 * clad::pop(_t3);
                  double _r3 = _r2 * clad::pop(_t4);
                  _d_x += _r3;
                  double _r4 = clad::pop(_t5) * _r2;
                  _d_x += _r4;
                  double _r5 = clad::pop(_t6) * _r_d1;
                  _d_interval += _r5;
                  _d_sum -= _r_d1;
                  if (_t2 == 1)               // <------------- START OF MODIFIED CODE
                  {
                      *_d_lower += _d_x;
                  }                          // <------------- END OF MODIFIED CODE
              }
          }
      }
      {
          double _r0 = _d_interval / _t0;
          *_d_upper += _r0;
          *_d_lower += -_r0;
          double _r1 = _d_interval * -_t1 / (_t0 * _t0);
          _d_num_points += _r1;
      }
  }
  ```
(Note: this is the code that I manually modified, the actual code after fixing may look different from this). 

Will try to fix the generated code now, and will share any updates or ask for any help needed if I am stuck.

**Comment by parth-07** [comment]
Hi @vaithak. Thank you for the detailed analysis and welcome to the project.

> While doing a reverse-mode AD, the code should be doing d_lower += dx in the end somewhere for this and turns out this is what is missing from the generated code for the gradient. 

Exactly!. You have found the root cause of the issue.

Your solution is good, but I think we can make some improvements knowing that `if (_t2 == 1)` will always be true (only) in the last iteration of the reverse-accumulation `for` loop. Instead of adding an `if (_t2 == 1)` condition in the reverse accumulation code of the `for` loop, what do you think of this solution?

Given a `for` loop:

```cpp
for (double x = lower; x <= upper; x += interval) {
  // ...
}
```

The for loop can be generalized as:

```cpp
for (initialization; condition; expression) {
 // ...
}
```

'initialization' statement would be executed one time, 'condition' and 'expression' statement would be executed once for each of the loop. Clad can generate reverse-accumulation code of the `for` loop as follows:

```cpp
for (; _t2; _t2--) { // _t2 is the loop counter
  // reverse-mode accumulation code of the loop body
  // reverse-mode accumulation code of the 'expression' statement
}
// reverse-mode accumulation code for the 'initialization' statement.
*_d_lower += _d_x; // Only this is new! Clad already does the other things.

**Comment by vaithak** [comment]
Hi @parth-07, you are right, just having this single statement will work. 
I mistakenly thought that `_d_x` was only available inside the nested scope inside the for loop that's why added that extra `if` condition. 
Thanks 👍🏼
