### ISSUE TITLE
What would it take to create Rust bindings?

### ISSUE THREAD

**Issue by igor-krawczuk** [vgvassilev/clad#487]
Hi,

I just found this project and I'm wondering how much effort it would be to extend this functionality to rust, which has a very easy FFI with C/C++ using the C ABI and uses LLVM as a backend. Does the method used work across FFI boundaries or does it rely on the compiler having a full AST available? (Note: Not a feature request, I'm just thinking of doing this myself and figured I'd ask the expert before banging my head against it)

Best regards,
Igor

**Comment by vgvassilev** [comment]
Hi @igor-krawczuk,

  Thanks for reaching out. 

  Frankly I do not see how having Rust bindings would work. Can you elaborate more?

  Clad works by rewriting clang's AST and requires at least the full function AST to be available. If you are thinking to start such a project yourself you should be prepared for a lot of work with compiler and language internals.

**Comment by igor-krawczuk** [comment]
I was expecting that, thanks for answering so quickly to an impulsive question!  Since [enzyme](https://enzyme.mit.edu/) works with LLVM IR and has [experimental Rust support](https://github.com/EnzymeAD/oxide-enzyme) but incomplete and not  easy to work with I was intrigued when I found your project. I guess one could maybe adopt the strategies to implement a [procedural macro](https://doc.rust-lang.org/reference/procedural-macros.html) which has access to the TokenStream and can get get a syntax tree via syn,but it would be a reimplementation then. Maybe once I'm done with my PhD^^"

**Comment by vgvassilev** [comment]
No worries, thanks for asking!

I don't know if you can get away just by a lexer-based implementation. I am getting slowly convinced that we might need some compiler representation which is suitable for AD and easy to convert from compiler's frontend and then pipe it in the backend. LLVM's mlir seems promising and I have been planning to do some investigations in that area. Let me know if you are interested and we can perhaps define some limited-scope project ;)
