### ISSUE TITLE
Question concerning performance wrt Ceres

### ISSUE THREAD

**Issue by ferdymercury** [vgvassilev/clad#501]
Hello, thanks for this tool!

One question, is there any advantage with regard to performance of using "clad" instead of other tools like "ceres" that have templated automated differentiation? (http://ceres-solver.org/automatic_derivatives.html#chapter-automatic-derivatives)

**Comment by vgvassilev** [comment]
Thanks for the question. AD tools can be categorized by how much work is done before program execution. AD typically starts by building a computational graph, or a directed acyclic graph of mathematical operations applied to an input. At one extreme, the tracing, or taping, approach constructs and processes the computational graph at the time of execution, each time a function is invoked. In contrast, the source transformation approach does as much as possible at compile time to create the derivative only once. The tracing approach is easier to implement and adopt into existing codebases. The source transformation approach has better performance, but usually covers a subset of the language.

The template metaprogramming is generally used to implement taping-based tools while clad is a source transformation tool. The tracing tools generally cannot optimize across statements and generally do not handle control flow.

**Comment by ferdymercury** [comment]
Thanks for the nice explanation. :)

(Please let me know if later on there is some benchmark comparison, I am just curious of how much the difference is at the end)

**Comment by vgvassilev** [comment]
It depends on the benchmarks. There is the ADBench benchmark suite which shows some benchmarks. Generally, source transformation tools are factors faster .
