### ISSUE TITLE
Move ROOT to the pushforward/pullback model 

### ISSUE THREAD

**Issue by vgvassilev** [vgvassilev/clad#510]
Here, we need to move https://github.com/root-project/root/blob/master/math/mathcore/inc/Math/CladDerivator.h to follow what has been done in Clad: https://github.com/vgvassilev/clad/blob/master/include/clad/Differentiator/BuiltinDerivatives.h where all functions are based on pushforwards and pullbacks.

**Comment by arora-vidushi** [comment]
Hello Vassil, 

To work on this issue, I have some doubts that I would like more information upon:

++ Does the root use CLAD latest version and has tests to check custom derivative? 
++ Also, if we change the custom derivative function in Root, will it break the existing tests?

Thanks,
Vidushi

**Comment by vgvassilev** [comment]
> Hello Vassil,
> 
> To work on this issue, I have some doubts that I would like more information upon:
> 
> ++ Does the root use CLAD latest version and has tests to check custom derivative?

Yes, it uses the last version of clad (v1.0).

 ++ Also, if we change the custom derivative function in Root, will it break the existing tests?

No, and that's the issue, this part has no test coverage in ROOT but I think we should develop some basic tests after we migrate.

**Comment by vgvassilev** [comment]
This issue is independent on the release of Clad and thus not a release blocker.

**Comment by vgvassilev** [comment]
This has been resolved. Thanks a lot @arora-vidushi!
