### ISSUE TITLE
Improve generation of variables and assignemnts

### ISSUE THREAD

**Issue by vgvassilev** [vgvassilev/clad#525]
We have the pattern:
```
double _t0;
...
_t0=...;
```
Instead we should generate `double _t0 = ...;`

This would significantly shorten the produced code snippets and make them more understandable.

**Comment by utkarshraj779** [comment]
Acoording to me in place of double _t0 if we want to make it more understandable e int(_to)-_to>0 then if condetion  type  float otherweise it read integer after that we understand what type of no is this

**Comment by utkarshraj779** [comment]
i want to contribute in this issue please assigned it to me.
@vgvassilev I am utkarsh kumar from iit kharagpur 3rd year student and i want to contribute in gsoc 2023. and i already mailled you please give me some idea that should be benificial to me i am thankful to you.
