### ISSUE TITLE
Fix the Clad usage command in documentation.

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#530]
Clad usage commands in Clad documentation ([https://clad.readthedocs.io/en/latest/user/InstallationAndUsage.html](https://clad.readthedocs.io/en/latest/user/InstallationAndUsage.html))  do not directly works. 
We should fix these commands and add more details/references explaining the command options.

**Comment by Abinash-bit** [comment]
Hey , @parth-07 , I am keenly interested in working with this issue . I had mailed you yesterday ,  and you asked me to fix issues and create issues . Please assign this issue.

**Comment by parth-07** [comment]
Hi @Abinash-bit,
We need to add the information about the command shown below to the documentation.

```
clang++ -o main.elf main.cpp -Xclang -add-plugin -Xclang clad -Xclang -load -Xclang /path/to/clad.so -I/path/to/clad/include -xc++
```
You can start working on the issue and create a pull-request once it's ready.

**Comment by Abinash-bit** [comment]
ok @parth-07 thank you so much.

**Comment by utkarshraj779** [comment]
@parth-07 Hlw parth i am utkarsh kumar i already mailed you and i want to work on this pr can i fix it.
