### ISSUE TITLE
Fix the Cmake command to build LLVM in Developers' documentation

### ISSUE THREAD

**Issue by Ris-Bali** [vgvassilev/clad#531]
The cmake command to build LLVM doesn't work directly(https://clad.readthedocs.io/en/latest/user/DevelopersDocumentation.html)
![image](https://user-images.githubusercontent.com/81592570/220244894-ecebf4a4-e4a2-4982-a2fd-76705681f962.png)
 
This can be solved by correcting the path to llvm sub-directory inside llvm-project.

**Comment by parth-07** [comment]
Hi Rishabh,
Thank you for opening the issue.
The following build instructions should work:
```
sudo -H pip install lit
git clone https://github.com/llvm/llvm-project.git
cd llvm-project
git checkout release/12.x
cd ../
mkdir obj inst
cd obj
cmake ../llvm-project/llvm -DCMAKE_BUILD_TYPE=Debug -DLLVM_TARGETS_TO_BUILD=host -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_INSTALL_PREFIX=../inst
make install
```

The instructions were missing a `cd` command.

**Comment by Ris-Bali** [comment]
Thanks for the reply @parth-07 I was able to build llvm by keeping obj and inst inside the llvm-project and by changing ../llvm-project/llvm to ../llvm but this seems to be a better solution; should I submit a PR making the above changes ? .

**Comment by parth-07** [comment]
Yes, sure.
Thank you for being proactive.
