### ISSUE TITLE
Ensure the project follows `.clang-format`

### ISSUE THREAD

**Issue by snprajwal** [vgvassilev/clad#537]
Edit: Since there already is a `.clang-format` file, the project can be formatted in it's current state in a PR. This will reduce noise in future contributions and prevent incremental reformatting of the project files.

**Comment by parth-07** [comment]
Clad already has a .clang-format file

**Comment by ro4i7** [comment]
Hello @parth-07 @vgvassilev 

To solve this issue follow these steps:
1. First, clone the repo on your machine, and navigate to the root directory of the repository.
2. Open your terminal and type "sudo apt-get install clang-format" if you don't have clang-format installed already.
3. Run the command "clang-format -style=file -i [filename]" on each file you want to format. You can also run "clang-format -style=file -i ." to format all files in the repository.
4. After you have formatted all the files, commit and push your changes to a new branch, and create a pull request with your changes.
5. Now the project is properly formatted and there won't be any future formatting issues.
