### ISSUE TITLE
Error in Building from source LLVM, Clang and Clad (development environment)

### ISSUE THREAD

**Issue by ShounakDas101** [vgvassilev/clad#541]
In README.md under Building from source LLVM, Clang and Clad (development environment)section I found these cmd line instructions. 

sudo -H pip install lit
git clone https://github.com/llvm/llvm-project.git src
cd src; git checkout llvmorg-13.0.0
cd /tools                                               -------------------------------> error at this line
git clone https://github.com/vgvassilev/clad.git clad
cd ../../../
mkdir obj inst
cd obj
cmake -S ../src/llvm -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE="Debug" -DLLVM_TARGETS_TO_BUILD=host -DCMAKE_INSTALL_PREFIX=../inst 
make && make install

cd /tools
This line is giving error because there is no tools directory.
![Screenshot from 2023-03-11 09-26-57](https://user-images.githubusercontent.com/108444232/224463685-632e74fa-c152-4acb-be81-7d4bb961acbd.png)

But there is a tools directory src/llvm/tools.
Do we have to go to this directory and run the rest of the commands 

git clone https://github.com/vgvassilev/clad.git clad
cd ../../../
mkdir obj inst
cd obj
cmake -S ../src/llvm -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE="Debug" -DLLVM_TARGETS_TO_BUILD=host -DCMAKE_INSTALL_PREFIX=../inst 
make && make install

**Comment by ShounakDas101** [comment]
Yes. I have checked and installed LLVM, CLAND and CLAD as follows:

sudo -H pip install lit
git clone https://github.com/llvm/llvm-project.git src
cd src; git checkout llvmorg-13.0.0
cd llvm/tools/
git clone https://github.com/vgvassilev/clad.git clad
cd ../../../
mkdir obj inst
cd obj
cmake -S ../src/llvm -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE="Debug" -DLLVM_TARGETS_TO_BUILD=host -DCMAKE_INSTALL_PREFIX=../inst
make && make install

NOTE: One has to set PATH properly, for that find out the "inst/" folder and add to $PATH
// PATH SET FOR LLVM
export PATH=$PATH:/home/shounak/My_Clad/inst/bin
export PATH=$PATH:/home/shounak/My_Clad/inst/lib
export PATH=$PATH:/home/shounak/My_Clad/inst/include
export PATH=$PATH:/home/shounak/My_Clad/inst/libexec
export PATH=$PATH:/home/shounak/My_Clad/inst/share

It worked for me.

**Comment by parth-07** [comment]
@ShounakDas101 Thank you for creating this issue and for the follow-up comment. 

I am pleasantly surprised that the commands you mentioned in the comment worked out of the box.
Can you please update the documentation with your commands? You can leave out the `export PATH` commands.

**Comment by ShounakDas101** [comment]
@parth-07 I think I have done the necessary changes from my part

**Comment by parth-07** [comment]
@ShounakDas101 Can you create a pull request on vgvassilev/clad?

**Comment by ShounakDas101** [comment]
@parth-07  I think I have made the necessary changes 
If anymore changes need to be made please let me know
