### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by brianpereboom** [vgvassilev/clad#561]
When running the example code from the readme file under "Forward mode - clad::differentiate", I get "/usr/include/clad/Differentiator/Differentiator.h:150: clad::CladFunction<F, FunctorT, EnablePadding>::CladFunction(CladFunctionType, const char*, FunctorType*) [with F = void (*)(double, double, clad::array_ref<void>, clad::array_ref<void>); FunctorT = clad::NoObject; bool EnablePadding = true; CladFunctionType = void (*)(double, double, clad::array_ref<void>, clad::array_ref<void>); FunctorType = clad::NoObject]: Assertion `f && "Must pass a non-0 argument."' failed." This is also the case for clad::estimate_error (which is the function I need).

**Comment by grimmmyshini** [comment]
Hi @brianpereboom, can you share the exact code file you are trying to compile? Thanks!

**Comment by grimmmyshini** [comment]
Can you also share the command you compiled this file with?

**Comment by brianpereboom** [comment]
`g++ -std=c++2a -I /full/path/to/include/ -fplugin=/full/path/to/lib/clad.so Sourcefile.cpp`

Sorry, I didn't save the exact command, but I used this command with the correct paths and source file. One thought I had was that g++ is incorrect and that I had to use clang, but I was already using g++ and wasn't sure if switching to clang++ would work.

**Comment by grimmmyshini** [comment]
Oh, I see now. So, since clad is a clang-based plugin, you can only compile and get the derivatives using clang. This is a command I like to use to compile my clad based programs:

```
clang -Xclang -add-plugin -Xclang clad -Xclang -load -Xclang ./path/to/clad.so -I../path/to/clad/include/ -xc++ -lstdc++ -lm Sourcefile.cpp
```
Let me know if this command works for you.

**Comment by brianpereboom** [comment]
It works. Thank you.

**Comment by vgvassilev** [comment]
Let's close this now!
