### ISSUE TITLE
Incorrect gradient generation

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#650]
Reproducible example:

```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>
#define show(x) std::cout << #x << ": " << x << "\n";

double fn(double u, double v) {
    double r = (u = v = u = 0);
    return r;
}

int main() {
    auto fn_grad = clad::gradient(fn);
    double du, dv;
    du = dv = 0;
    fn_grad.execute(3, 5, &du, &dv);
    show(du);
    show(dv);
    auto d_fn_u = clad::differentiate(fn, "u");
    show(d_fn_u.execute(3, 5));
    auto d_fn_v = clad::differentiate(fn, "u");
    show(d_fn_v.execute(3, 5));
}
```

Output:
```
du: -1
dv: 0
d_fn_u.execute(3, 5): 0
d_fn_v.execute(3, 5): 0
```

Incorrect gradient is generated for both the current master and the TBR branch.

**Comment by devilkiller-ag** [comment]
Hi @parth-07, I superficially examined your issue. The issue seems to be with line `auto d_fn_v = clad::differentiate(fn, "u");`. It should be `auto d_fn_v = clad::differentiate(fn, "v");`. However, I am unsure if this is the real cause of the error as I haven't run the example yet.

**Comment by vaithak** [comment]
I am not sure in which commit, but this is fixed. The result is correct now.

**Comment by vgvassilev** [comment]
Can we add a test and close this issue?

**Comment by vaithak** [comment]
My bad; there was a difference in what I was testing and the snippet in this issue. The result is still wrong, as mentioned in the issue.
