### ISSUE TITLE
Compiler error related to `new` and/or pointers

### ISSUE THREAD

**Issue by maxaehle** [vgvassilev/clad#654]
**Minimal example**: Compile the following code with Clang++ with the clad plugin:
```c++
#include <iostream>
#include "clad/Differentiator/Differentiator.h"

struct T {};

double f(double x){
  T* y = new T{};
  return x;
}

int main(){
  auto f_dx = clad::gradient(f, "x");
  double d;
  f_dx.execute(3,&d);
}
```
**Expected behavior**: Code compiles.

**Observed behavior**: Compiler error:
```
heapallocation.cpp:7:10: warning: attempted to differentiate unsupported statement, no changes applied
  T* y = new T{};
         ^
clang: /home/aehle/clad/src/lib/Differentiator/StmtClone.cpp:500: clang::Stmt* clad::utils::StmtClone::VisitStmt(clang::Stmt*): Assertion `0 && "clone not fully implemented"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
...
```

**Further information**: An analogous error message shows up if the type `T` is replaced by e.g. `char` or `double`. 

**Setup**: Clad built from the GitHub master branch at commit https://github.com/vgvassilev/clad/commit/1bdd261ea71163b3e8074dca4018e94a481a1c50 on Ubuntu 22.04 with Clang 11.

**Comment by parth-07** [comment]
Hi @maxaehle

Thank you for reporting this issue. However, it's a known limitation that Clad does not support pointers in the reverse-mode. I believe @vaithak is working on the pointer support.

**Comment by parth-07** [comment]
One way to add support for `new` and `delete` keywords is to use custom derivatives functionality. Currently, clad supports custom derivatives functionality for many operators (`+`, `+=`, `*`, and so on). However, currently, it does not support custom derivatives for `new`, `delete` and `delete []`. If support for custom derivatives for these operators is added, then perhaps we can support `new` and `delete` for **primitive** types by providing custom derivatives as follows:

```cpp
template <typename T>
clad::ValueAndPushforward<T *, T *> operator_new_pushforward(T arg, T d_arg) {
  return {new T (arg), new T (d_arg)};
}

void operator_delete_pushforward(T &arg, T &d_arg) {
  delete arg;
  delete d_arg;
}

template<typename R, typename T>
void operator_new_pullback(T u, R d_y, T *d_u) {
  d_u += d_y;
}
```

We will need to improve these custom derivatives to support all valid cases. We can perhaps support `malloc` and related functions this way as well. @vaithak What do you think about using custom derivatives for supporting memory allocations?
