### ISSUE TITLE
Issue useful diagnostic when trying to differentiate function w/o definition.

### ISSUE THREAD

**Issue by vgvassilev** [vgvassilev/clad#67]
For example:
```cpp
double foo(double);
clad::differentiate(foo,0);
```

We should probably have a similar to [this](https://github.com/vgvassilev/clad/blob/112a00fdb6f05b4b230c35fa67819d9b9b2ec02b/lib/Differentiator/DerivativeBuilder.cpp#L522-L528) check earlier (on a DiffPlanner level).

Currently we just crash ;)

**Comment by efremale** [comment]
This is fixed now.

**Comment by vgvassilev** [comment]
Do you know in which commit?

**Comment by efremale** [comment]
I believe #109.
