### ISSUE TITLE
Clad crashes on differentiating a call to an empty function with reference arguments

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#704]
Clad crashes when differentiating a call to an empty function that has reference arguments. It's a very specific case :'). 

Reproducible example:
```cpp
#include "clad/Differentiator/Differentiator.h"

void emptyFn(double &u, double v) {}

double fn(double u, double v) {
    emptyFn(u, v);
    return u + v;
}

int main() {
    auto d_fn = clad::gradient(fn);
}
```

**Comment by vaithak** [comment]
This seems to be already fixed, added a test to verify and ensure its correctness in future: https://github.com/vgvassilev/clad/pull/799
