### ISSUE TITLE
Incorrect derivative when loops contains `continue`

### ISSUE THREAD

**Issue by parth-07** [vgvassilev/clad#710]
Reproducible example:
```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>

#define show(x) std::cout << #x << ": " << x << "\n";

double fn(double u, double v) {
    double res = 11 * u;
    for (int i = 0; i < 3; i++) {
        res += u * i;
        continue;
    }
    return res;
}

int main() {
    auto d_fn = clad::gradient(fn);
    double u = 3, v = 5;
    double du, dv;
    du = dv = 0;
    d_fn.execute(u, v, &du, &dv);
    show(du);
    show(dv);
}
```

**Output**
du: 20
dv: 0

**Expected output**
du: 14
dv: 0

**Comment by Deepanshu9376** [comment]
To achieve the expected output, modify the loop to only add u to res in the first iteration:
double fn(double u, double v) {
  double res = 11 * u;
  for (int i = 0; i < 3; i++) {
    if (i == 0) {
      res += u * i;
    }
    continue;
  }
  return res;
}

**Comment by vgvassilev** [comment]
@Deepanshu9376, please read the our [wiki](https://github.com/vgvassilev/clad/wiki/GSoC-2024#what-not-to-do-and-will-give-you-negative-points) for guidelines what not to do when trying to engage with our community. Please pick up an issue or two and try to solve them and possibly ask clarification questions under the issue you are working on for a day or two. Do not comment under every issue you find interesting.

**Comment by Deepanshu9376** [comment]
Sorry for this will take care from next time
