### ISSUE TITLE
Add support for range-based for loops.

### ISSUE THREAD

**Issue by vgvassilev** [vgvassilev/clad#723]

**Comment by 7070Shreyash** [comment]
Hey @vgvassilev  , Could you provide guidance on resolving this problem? I'm new to the CLAD codebase and would appreciate assistance

**Comment by krathul** [comment]
I would like to work on this issue @vgvassilev. I guess its only the body of the range-based for loop that can be differentiated right?

**Comment by krathul** [comment]
@vgvassilev from what I can understand I need to first differentiate initialization statement, and then the body. And finally construct the ranged for loop block which uses derivates. 
Or will it be possible to transform the range-based for loop to a normal for loop?
