### ISSUE TITLE
Add a 32bit CI build

### ISSUE THREAD

**Issue by vgvassilev** [vgvassilev/clad#748]
That will help us catch issues such as #747. Maybe using QEMU will work assuming that we can install the llvm binaries: https://docs.docker.com/build/ci/github-actions/multi-platform/

**Comment by Krishna-13-cyber** [comment]
Hi @vgvassilev,
I will try to get this done. We will need a dockerized image(clad) for the workflow.

**Comment by vgvassilev** [comment]
@Krishna-13-cyber, I suspect you can find on github already systems that use qemu to build in 32 bits. We probably need something like: https://github.com/flintlib/flint/pull/1564/

**Comment by Krishna-13-cyber** [comment]
> @Krishna-13-cyber, I suspect you can find on github already systems that use qemu to build in 32 bits. We probably need something like: [flintlib/flint#1564](https://github.com/flintlib/flint/pull/1564)

Yes thanks, I will refer this.
