### ISSUE TITLE
Using std::array inside functions to be differentiated?

### ISSUE THREAD

**Issue by a-jp** [vgvassilev/clad#829]
Hi,

Can I use std::array to hold data that is accessed by functions that are differentiated?  

```c++
double f(double x, double y)
{
  double a[2];
  a[0] = 5;
  a[1] = 4;
  //std::array<double, 2> a{{5, 4}}; // fails
  return a[0] * x * y;
}
```

Thanks

**Comment by vaithak** [comment]
Hi @a-jp, std::array is not yet supported in clad. We are aware of this, along with many other stl features and plan to add support for them in the near future.

**Comment by a-jp** [comment]
Ok thanks

**Comment by vgvassilev** [comment]
I'd like to keep this issue open since supporting `std::array` is an immediate goal for the project.
