### ISSUE TITLE
Incorrect type of zero returned in VisitCallExpr

### ISSUE THREAD

**Issue by ovdiiuv** [vgvassilev/clad#908]
Return type of zero that is returned in case function's arguments are literals is set to be int, but has to depend on function's return type.
Differentiating the function:
`float f1(double x, double y){
    return fmax(x, NAN);
}`
gives a warning 
`Unsupported declaration
      typedef typename __gnu_cxx::__promote_2<_Tp, _Up>::__type __type;`

**Comment by parth-07** [comment]
Can you please give an example of where it is incorrect and why it is incorrect? Does it produce an incorrect derivative in any case? If so, can you please add an example?
