### ISSUE TITLE
Would it be possible to implement forward mode by simply replacing all numerical types with dual-number types?

### ISSUE THREAD

**Issue by efremale** [vgvassilev/clad#99]
The idea is to replace each type `RealT` with the type `dual<RealT, RealT>`, where `dual` has overloaded operators such that the first element is the same as the original value and the second element is the value of its derivative. This is easy to achieve by employing basic differentiation rules for operators.

On the first sight, it appears to be a much easier way of supporting more general C++ constructs as they need not be treated separately anymore.

Similar idea is in "Automatic Differentiation in 10 minutes with Julia": https://www.youtube.com/watch?v=vAp6nUMrKYg&t=683s

**Comment by vaithak** [comment]
This can be done theoretically, but this would mean doing a major redesign of how the clad interface (and its internal workings) and I don't see any advantage of doing that.
Given that this is an old issue, and the fact that clad now has comprehensive support in forward mode AD without explicitly defining the Dual Numbers structure, maybe we can close this issue as not planned?
cc: @parth-07 @vgvassilev

**Comment by vgvassilev** [comment]
I agree it with that assessment. Let's close it as you suggest.
